language: ruby
dist: trusty
sudo: false
cache: bundler
rvm:
  - 2.3.2
  - 2.2.6
  - 2.1.10
  - jruby-9.1.5.0
  - ruby-head
  - rbx-3
after_success:
  # Send coverage report from the job #1 == current MRI release
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
before_install: gem update bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
notifications:
  email:
    recipients:
      - fg@flashgordon.ru
    on_success: change
    on_failure: always
    on_start: false     # default: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
